global:
  scrape_interval: 20s  # default 1m 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']  
  
  - job_name: 'linux'
    static_configs:
      - targets: ['ps-prom-ub1804:9100']
      
  - job_name: 'batch'
    static_configs:
      - targets: ['ps-prom-ub1804:8080']

  - job_name: 'windows'
    scrape_timeout: 15s  # default 10 s
    static_configs:
      - targets: ['ps-prom-win2019:9182']

  - job_name: 'web'
    metrics_path: /metrics
    scheme: http  # can include TLS and auth for HTTPS
    static_configs:
      - targets: ['ps-prom-win2019:8088']
